# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: cmd-utils 1.3.3 ruby lib

Gem::Specification.new do |s|
  s.name = "cmd-utils"
  s.version = "1.3.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Alan K. Stebbens"]
  s.date = "2017-01-11"
  s.description = "Several ruby libraries for building command-line utilities."
  s.email = "aks@stebbens.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "cmd-utils.gemspec",
    "lib/arg-utils.rb",
    "lib/cmd-utils.rb",
    "lib/error-utils.rb",
    "lib/lookup.rb",
    "lib/run-utils.rb",
    "lib/ssh-utils.rb",
    "lib/talk-utils.rb",
    "test/helper.rb",
    "test/test-lookup.rb",
    "test/test-run-utils.rb",
    "test/test-talk-utils.rb"
  ]
  s.homepage = "http://bitbucket.org/aks_/cmd-utils"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Utilities for building CLIs"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<minitest>, [">= 5.10.1"])
      s.add_development_dependency(%q<rdoc>, [">= 5.0.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 2.3.2"])
    else
      s.add_dependency(%q<minitest>, [">= 5.10.1"])
      s.add_dependency(%q<rdoc>, [">= 5.0.0"])
      s.add_dependency(%q<bundler>, [">= 1.0"])
      s.add_dependency(%q<jeweler>, [">= 2.3.2"])
    end
  else
    s.add_dependency(%q<minitest>, [">= 5.10.1"])
    s.add_dependency(%q<rdoc>, [">= 5.0.0"])
    s.add_dependency(%q<bundler>, [">= 1.0"])
    s.add_dependency(%q<jeweler>, [">= 2.3.2"])
  end
end

